from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('adminhome/',views.adminhome),
    path('district/',views.district),
    path('district_insert/',views.district_insert,name='district_insert'),
    path('view_district/',views.view_district,name='view_district'),
    path('editdistrict/<districtid>/',views.editdistrict,name='editdistrict'),
    path('deletedistrict/<districtid>',views.deletedistrict,name='deletedistrict'),
    path('location/',views.location,name='location'),
    path('location_register/',views.location_register,name='location_register'),
    path('viewlocation/',views.viewlocation,name='viewlocation'),
    path('filllocation/',views.filllocation,name='filllocation'),
    path('editlocation/<locationid>/',views.editlocation,name='editlocation'),
    path('deletelocation/<locationid>/',views.deletelocation,name='deletelocation'),
    path('categories/',views.categories,name='categories'),
    path('category_insert/',views.category_insert,name='category_insert'),
    path('viewcategory/',views.viewcategory,name='viewcategory'),
    path('editcategory/<cid>/',views.editcategory,name='editcategory'),
    path('deletecategory/<cid>/',views.deletecategory,name='deletecategory'),
    path('viewcompany/',views.viewcompany,name='viewcompany'),
    path('deletecompany/<cid>/',views.deletecompany,name='deletecompany'),
    path('acceptcompany/<id>',views.acceptcompany,name='acceptcompany'),
    path('rejectcompany/<id>',views.rejectcompany,name='rejectcompany'),
    path('deletecompany/<cid>/',views.deletecompany,name='deletecompany'),
    path('customerreport/',views.customerreport,name='customerreport'),
    path('customerreport_excel/',views.customerreport_excel,name='customerreport_excel'),
    path('datewisepayreport/',views.datewisepayreport,name='datewisepayreport'),
    path('datewisepayreport_excel/',views.datewisepayreport_excel,name='datewisepayreport_excel'),
    path('datewisebookingreport/',views.datewisebookingreport,name='datewisebookingreport'),
    path('datewisebookingreport_excel/',views.datewisebookingreport_excel,name='datewisebookingreport_excel'),
    path('reportcategorycount/',views.reportcategorycount,name='reportcategorycount'),
    path('reportcategorycount_piechart/',views.reportcategorycount_piechart,name='reportcategorycount_piechart'),
]