# Generated by Django 5.2.7 on 2026-01-14 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestapp', '0011_tbl_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_service',
            fields=[
                ('serviceid', models.IntegerField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=100)),
                ('totalamount', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=100)),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_company')),
            ],
        ),
    ]
