# Generated by Django 5.2.7 on 2026-01-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_service',
            name='serviceid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
