# Generated by Django 5.2.7 on 2026-01-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0005_alter_tbl_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_service',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
