# Generated by Django 5.2.7 on 2025-11-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_district',
            fields=[
                ('districtid', models.AutoField(primary_key=True, serialize=False)),
                ('districtname', models.CharField(max_length=50)),
            ],
        ),
    ]
