# Generated by Django 5.2.7 on 2025-12-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=50)),
            ],
        ),
    ]
