# Generated by Django 5.2.7 on 2025-12-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_tbl_category'),
        ('guestapp', '0002_tbl_login_rename_placeid_user_locationid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_login',
        ),
    ]
