# Generated by Django 5.2.7 on 2026-01-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyapp', '0007_tbl_service_categoryid'),
        ('guestapp', '0018_alter_tbl_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('bookingstatus', models.CharField(max_length=50)),
                ('bookingdate', models.DateField()),
                ('serviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.tbl_service')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.user')),
            ],
        ),
    ]
