# Generated by Django 5.2.7 on 2026-01-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0018_alter_tbl_company_image'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='loginid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login'),
        ),
    ]
