# Generated by Django 5.2.7 on 2026-01-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_tbl_booking_loginid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='loginid',
        ),
    ]
