# Generated by Django 5.2.7 on 2026-01-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_tbl_booking_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentdate', models.DateField()),
                ('totalamount', models.IntegerField()),
                ('paymentstatus', models.CharField(max_length=50)),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_booking')),
            ],
        ),
    ]
