# Generated by Django 5.2.7 on 2026-02-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0018_alter_tbl_company_image'),
        ('userapp', '0005_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_credit',
            fields=[
                ('creditid', models.AutoField(primary_key=True, serialize=False)),
                ('creditamount', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.user')),
            ],
        ),
    ]
