# Generated by Django 5.2.7 on 2026-02-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_tbl_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_credit',
            name='creditamount',
            field=models.IntegerField(default=0),
        ),
    ]
