# Generated by Django 5.2.7 on 2025-12-15 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0004_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_login')),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_location')),
            ],
        ),
    ]
