# Generated by Django 5.2.7 on 2026-01-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_delete_tbl_login'),
        ('guestapp', '0002_tbl_login_rename_placeid_user_locationid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('compid', models.AutoField(primary_key=True, serialize=False)),
                ('compname', models.CharField(max_length=50)),
                ('verificationstatus', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=11)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login')),
            ],
        ),
    ]
