# Generated by Django 5.2.7 on 2026-01-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_tbl_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_company',
            old_name='phoneno',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='city',
            field=models.CharField(default='NIL', max_length=50),
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='state',
            field=models.CharField(default='NIL', max_length=50),
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='street',
            field=models.CharField(default='NIL', max_length=50),
        ),
    ]
