# Generated by Django 5.2.7 on 2026-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0004_rename_phoneno_tbl_company_contact_tbl_company_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_company',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_company',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
