# Generated by Django 5.2.7 on 2026-01-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0005_alter_tbl_company_city_alter_tbl_company_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='username',
            field=models.CharField(default='nu', max_length=50),
        ),
    ]
