# Generated by Django 5.2.7 on 2026-01-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0006_tbl_company_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
