# Generated by Django 5.2.7 on 2026-01-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0007_alter_tbl_company_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='description',
            field=models.CharField(default='mil', max_length=200),
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='image',
            field=models.ImageField(default='../1.png', upload_to=''),
        ),
    ]
