# Generated by Django 5.2.7 on 2026-01-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0008_tbl_company_description_tbl_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_company',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
