# Generated by Django 5.2.7 on 2026-01-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0009_alter_tbl_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='status',
            field=models.CharField(default='In Queue', max_length=50),
        ),
    ]
