# Generated by Django 5.2.7 on 2026-01-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0010_tbl_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_login',
            name='status',
            field=models.CharField(default='In Queue', max_length=50),
        ),
    ]
