# Generated by Django 5.2.7 on 2026-01-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0011_tbl_login_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_company',
            name='verificationstatus',
        ),
    ]
