# Generated by Django 5.2.7 on 2026-01-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0012_remove_tbl_company_verificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
