# Generated by Django 5.2.7 on 2026-01-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0014_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../images/'),
        ),
    ]
