# Generated by Django 5.2.7 on 2026-01-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0015_alter_tbl_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../media/'),
        ),
    ]
