# Generated by Django 5.2.7 on 2026-01-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0016_alter_tbl_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company',
            name='image',
            field=models.ImageField(upload_to='../media/'),
        ),
    ]
