# Generated by Django 5.2.7 on 2026-02-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0018_alter_tbl_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
